[package]
name        = "advent"
version     = "0.1.0"
authors     = ["Aldrin J D'Souza <code@aldrin.co>"]
description = "Solutions to Advent of Code puzzles"
license     = "MIT"
readme      = "README.md"
homepage    = "https://github.com/aldrin/advent"
keywords    = ["puzzles"]

[dependencies]
